// Authenticaion
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

// Role
export const ROLE_COUNT = "ROLE_COUNT";

// Group
export const GROUP_COUNT = "GROUP_COUNT";

// modal
export const MODAL_COUNT_INCREMENT = "MODAL_COUNT_INCREMENT";
export const MODAL_COUNT_DECREMENT = "MODAL_COUNT_DECREMENT";
export const COUNTABLE = 0;

// User
export const USER_COUNT = "USER_COUNT";
export const USER_DATA = "USER_DATA";
export const USER_CREDIT_INCREMENT = "USER_CREDIT_INCREMENT";

//Organization
export const ORGANIZATION_COUNT = "ORGANIZATION_COUNT";
export const GET_LAT_LNG = "GET_LAT_LNG";
export const IS_NUMBER_ASSIGNED = "IS_NUMBER_ASSIGNED";
export const FETCH_ALL_ORGANIZATIONS_LIST = "FETCH_ALL_ORGANIZATIONS_LIST";

//Association
export const ASSOCIATION_COUNT = "ASSOCIATION_COUNT";

// Automation
export const AUTOMATION_COUNT = "AUTOMATION_COUNT";

//User
export const USER_FILTER = "USER_FILTER";

// Permission
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";

// Contacts
export const CONTACTS_COUNT = "CONTACTS_COUNT";
export const CONTACTS_MODAL_ID = "CONTACTS_MODAL_ID";
export const CONTACTS_MODAL_RESET = "CONTACTS_MODAL_RESET";
export const CONTACTS_MODAL_ALIAS = "CONTACTS_MODAL_ALIAS";

// Notification
export const NOTIFICATION_DATA = "NOTIFICATION_DATA";
export const NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED";
export const NOTIFICATION_READ = "NOTIFICATION_READ";
export const NOTIFICATION_CLICK_CONTACT = "NOTIFICATION_CLICK_CONTACT";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const MESSAGE = "MESSAGE";

//Credit
export const SHOW_CREDIT_RESTRICTION = "SHOW_CREDIT_RESTRICTION";
export const HIDE_CREDIT_RESTRICTION = "HIDE_CREDIT_RESTRICTION";
export const SEND_CREDIT_GIFT_POINT = "SEND_CREDIT_GIFT_POINT";
export const RESET_SEND_CREDIT_GIFT_POINT_RESPONSE =
	"RESET_SEND_CREDIT_GIFT_POINT_RESPONSE";

export const OPEN_HEADER_MODAL = "OPEN_HEADER_MODAL";
export const CLOSE_HEADER_MODAL = "CLOSE_HEADER_MODAL";
export const OPEN_BODY_MODAL = "OPEN_BODY_MODAL";
export const CLOSE_BODY_MODAL = "CLOSE_BODY_MODAL";
export const OPEN_USER_MODAL = "OPEN_USER_MODAL";
export const CLOSE_USER_MODAL = "CLOSE_USER_MODAL";

// Filter request
// export const FETCH_FILTER_REQUEST = "FETCH_FILTER_REQUEST";
export const FETCH_FILTER_SUCCESS = "FETCH_FILTER_SUCCESS";
export const FETCH_FILTER_FAILURE = "FETCH_FILTER_FAILURE";
export const SAVE_FILTER_LIST = "SAVE_FILTER_LIST";
export const FETCH_FILTER_LIST = "FETCH_FILTER_LIST";
export const DELETE_STATUS_LIST = "DELETE_STATUS_LIST";

//Tag list
export const FETCH_TAG_LIST_DATA = "FETCH_TAG_LIST_DATA";
export const SAVE_TAG_TO_LIST = "SAVE_TAG_TO_LIST";
export const DELETE_TAG_FROM_LIST = "DELETE_TAG_FROM_LIST";
export const TAG_SERVICE_REQUEST_FAILED = "TAG_SERVICE_REQUEST_FAILED";
export const APPOINTMENT_SAVE_TAG_DATA = "APPOINTMENT_SAVE_TAG_DATA";
export const APPOINTMENT_REMOVE_TAG_DATA = "APPOINTMENT_REMOVE_TAG_DATA";

// Subject request
// export const FETCH_SUBJECT_REQUEST = "FETCH_SUBJECT_REQUEST";
export const FETCH_SUBJECT_SUCCESS = "FETCH_SUBJECT_SUCCESS";
export const FETCH_SUBJECT_FAILURE = "FETCH_SUBJECT_FAILURE";
export const SAVE_SUBJECT = "SAVE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const FETCH_CUSTOMER_LIST = "FETCH_CUSTOMER_LIST";
export const EDIT_CUSTOMER_FIELD = "EDIT_CUSTOMER_FIELD";

// Email template
// export const FETCH_TEMPLATE_REQUEST = "FETCH_TEMPLATE_REQUEST";
export const FETCH_TEMPLATE_SUCCESS = "FETCH_TEMPLATE_SUCCESS";
export const FETCH_TEMPLATE_FAILURE = "FETCH_TEMPLATE_FAILURE";
export const SAVE_EMAIL_TEMPLATE = "SAVE_EMAIL_TEMPLATE";
export const DELETE_EMAIL_TEMPLATE = "DELETE_EMAIL_TEMPLATE";
export const UPDATE_EMAIL_TEMPLATE = "UPDATE_EMAIL_TEMPLATE";