// Authenticaion
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
// Role
export const ROLE_COUNT = "ROLE_COUNT";
// Group
export const GROUP_COUNT = "GROUP_COUNT";
// User
export const USER_COUNT = "USER_COUNT";
export const USER_DATA = "USER_DATA";
export const USER_CREDIT_INCREMENT = "USER_CREDIT_INCREMENT";
//Organization
export const ORGANIZATION_COUNT = "ORGANIZATION_COUNT";
export const GET_LAT_LNG = "GET_LAT_LNG";
//Association
export const ASSOCIATION_COUNT = "ASSOCIATION_COUNT";
// Automation
export const AUTOMATION_COUNT = "AUTOMATION_COUNT";
//User
export const USER_FILTER = "USER_FILTER";
// Permission
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
// Contacts
export const CONTACTS_COUNT = "CONTACTS_COUNT";
export const CONTACTS_MODAL_ID = "CONTACTS_MODAL_ID";
export const CONTACTS_MODAL_RESET = "CONTACTS_MODAL_RESET";
// Notification
export const NOTIFICATION_DATA = "NOTIFICATION_DATA";
export const NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED";
export const NOTIFICATION_READ = "NOTIFICATION_READ";
export const NOTIFICATION_CLICK_CONTACT = "NOTIFICATION_CLICK_CONTACT";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const MESSAGE = "MESSAGE";
//Credit
export const SHOW_CREDIT_RESTRICTION = "SHOW_CREDIT_RESTRICTION";
export const HIDE_CREDIT_RESTRICTION = "HIDE_CREDIT_RESTRICTION";
