const UserControlsRoles = () => {
  return (
    <div className="dashInnerUI">
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
      <p>User Control Roles</p>
    </div>
  );
};

export default UserControlsRoles;
